apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: gitops
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
